baseURL = "https://korsak.xyz/"
languageCode = "pl-pl"
title = "Jakub Korsak"
disqusShortname = "korsakxyz"

[permalinks]
  blog = "/:filename/"

[menu]
  [[menu.main]]
    url = "/zapisy/"
    name = "Zapisy na zajęcia"
    weight = 1
  [[menu.main]]
    url = "/blog/"
    name = "Blog"
    weight = 2

[params]
  dateFormat = "Jan 2, 2006"
