baseURL: 'https://blog.korsak.xyz/'
languageCode: pl-pl
title: Jakub Korsak
permalinks:
  blog: '/blog/:contentbasename/'
menu:
  main:
    - url: /blog/
      name: Blog
      weight: 1
params:
  dateFormat: 'Jan 2, 2006'
  author:
    name: Jakub Korsak

